image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore

tasks:
  - name: Set env
    command: >
      cp .env.dist .env;
      source .env;
  - name: Composer
    command: >
      composer install;
  - name: Setup DB
    command: >
      mysql -e "CREATE DATABASE IF NOT EXISTS $DATABASE_NAME";
      mysql -e "CREATE USER '$DATABASE_USER'@'localhost' IDENTIFIED BY '$DATABASE_PASSWORD';";
      mysql -e "GRANT ALL PRIVILEGES ON * . * TO '$DATABASE_USER'@'localhost';";
      mysqladmin reload;
  - name: Start Apache
    command: >
      apachectl start;
